# RunRealm Netlify Configuration
# Minimal deployment config following Core Principles: ENHANCEMENT FIRST, DRY, CLEAN

[build]
  # Use specific web build command to avoid mobile app dependencies
  command = "npm run build:web"
  # Webpack outputs to public/ directory
  publish = "public"
  # Skip builds for non-functional changes
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF || exit 1"

# Exclude mobile app from web builds to avoid React Native dependency conflicts
[build.environment]
  # Only install dependencies needed for web build
  NETLIFY_USE_YARN = "false"
  NODE_VERSION = "18"

# SPA Routing & API Proxy (order matters - specific rules first)
[[redirects]]
  # Proxy API calls to Hetzner backend (now with SSL)
  from = "/api/*"
  to = "https://runrealm.coupondj.fun/api/:splat"
  status = 200
  force = false

# Remove problematic asset redirects that cause MIME type issues
# Let Netlify handle missing assets naturally with proper 404s

[[redirects]]
  # SPA fallback - serve index.html for all client-side routes
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security & Performance Headers
[[headers]]
  for = "/*"
  [headers.values]
    # CORS for external API access (Mapbox, Web3 providers)
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS, PUT, PATCH, DELETE"
    Access-Control-Allow-Headers = "Content-Type, Authorization, X-Requested-With"
    # Security hardening
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains"

# HTML files should not be cached to prevent stale references
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"

# Root index.html gets extra aggressive cache prevention
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Last-Modified = "Thu, 01 Jan 1970 00:00:00 GMT"
    ETag = ""

# MIME Type Headers (CRITICAL FIX for Chrome/Brave compatibility)
# Using individual headers for better Netlify compatibility
# MIME Type Headers (CRITICAL FIX) - Alternative syntax
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.css"
  [headers.values]
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.json"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

[[headers]]
  for = "/*.map"
  [headers.values]
    Content-Type = "application/json; charset=utf-8"

# Cache headers for static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache optimization for static assets
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/apple-touch-icon*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"